popup showing the image in a bigger size when the carousel images are…
hlxsites/realmadrid pull request #107
Opened 2023-05-26 13:41 UTC by kacemait

Images with higher resolution still need to be uploaded  as content - The button Compartir/Share has not been implemented.

Fix [#31](https://github.com/hlxsites/realmadrid/issues/31)

Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-127
- After: https://31-add-popup-to-carousel-block--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-127

2023-05-26 15:58 UTC, chicharr reviewed
Hi @kacemait 
please upload some images with higher resolution to double check that it works as expected.
And also validate that it works well when the page is RTL (Arabic), in this case I think the X to close the dialog should be displayed on the left side

2023-05-26 17:54 UTC, kacemait commented
Hi @chicharr, yes I already tested it with a higher resolution image (the photo of the Bernabéu Stadium) and it works as expected.
Yes I will work on the Arabic version part.

2023-05-29 17:08 UTC, vdua requested changes

2023-05-29 17:08 UTC, vdua commented on blocks/carousel/carousel.css
> +  left: 0;
`inset-inline-start:0`

2023-05-29 17:08 UTC, vdua commented on blocks/carousel/carousel.css
> +  right: 21px;
`inset-inline-end:21px`

2023-05-29 17:08 UTC, vdua commented on blocks/carousel/carousel.css
> +  left: 21px;
this css rule will not be needed if you choose the `inset-inline-end` property

2023-05-29 17:08 UTC, vdua commented on blocks/carousel/carousel.css
> +  padding: 22px 70px 21px 17px;
use `padding-inline-end` and `padding-inline-start` properties

2023-05-29 17:08 UTC, vdua commented on blocks/carousel/carousel.js
> +      }
you would not need that as we are adding rtl at the body level. You can check that as well if needed somewhere

2023-05-29 17:08 UTC, vdua commented on blocks/carousel/carousel.js
> +      const containerDiv = document.createElement('div');
nitpick: I have realised that using string templates improves code readability
```
wrapDiv.innerHTML = `<div class=photo-container>
  <div class=photo-content>`
  ..
  ...
```

2023-06-01 12:19 UTC, kacemait commented
@vdua , thanks for this CSS best practices. I'm learning a lot :)

2023-06-01 12:32 UTC, kacemait commented on blocks/carousel/carousel.js
> +      const containerDiv = document.createElement('div');
I agree that using `document.createElement` and `appendChild` is more verbose and can lead to less readable code for complex structures. However, it's more explicit about the relationships between elements and allows more control when modifying elements. This can make the code easier to maintain in the long run, especially when dealing with dynamic content that needs to be updated or interacted with regularly.

2023-06-01 15:52 UTC, chicharr commented
Closing PR as the feature was implemented in a different one

2023-06-01 15:52 UTC, closed without merging