initial css structure
hlxsites/realmadrid pull request #7
Opened 2023-04-24 16:24 UTC by msagolj

Inital css structure , for mobile, desktop and wide desktop.

Fix #3

Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/
- After: https://issue-3--realmadrid--hlxsites.hlx.page/

2023-04-25 06:37 UTC, solaris007 commented
should probably establish early on variables for font-weights, font-sizes, colors, etc.

2023-04-25 10:03 UTC, chicharr requested changes
Hi @msagolj 
could you please check the padding /margin of the main content for mobile? it doesn't match the one from the original website.

<img width="1599" alt="Screenshot 2023-04-25 at 11 58 54" src="https://user-images.githubusercontent.com/43381734/234243865-8d6936b9-9ddb-48d8-989f-01bcdcf1ccfb.png">

Also please configure your IDE to remove trailing spaces and use 2 space indentation, instead of 4. If you are using Visual Studio Code I can help you with that

2023-04-25 14:25 UTC, msagolj commented
@chicharr

> could you please check the padding /margin of the main content for mobile? it doesn't match the one from the original website.

 I didn't add any padding/margin in a first step as they define the margins/paddings on each  div container e.g:
 
![image](https://user-images.githubusercontent.com/37147400/234305842-10026c84-c5d4-4afd-a508-cc5f168d481e.png)
and they are not even the same everywhere :) 

> Also please configure your IDE to remove trailing spaces and use 2 space indentation, instead of 4.
Sorry forgot to run the npm install and install the lint extensions for this workspace. should be fixed with next commit.

2023-04-27 07:13 UTC, chicharr approved these changes

2023-04-27 07:14 UTC, merged

2023-04-27 07:14 UTC, vdua commented on styles/styles.css
> +  border-bottom: 4px solid #0255A5;
We are using h2 in the hero block as well and this adds a border there as well. So I think we need to update the [styling of the h2](https://github.com/hlxsites/realmadrid/blob/main/blocks/hero/hero.css#L46) in the hero block there as well. 

For the vip areas section this is the styling that works

```
main .section .default-content-wrapper h2 {
  margin: 0;
  padding: 0;
  width: 40%;
  margin-bottom: 21px; /** for desktop and 15px for mobile */
  border-left: 0;
  text-align: left;
  border-right: 4px solid transparent; 
  text-transform: uppercase;
  font-family: var(--heading-font-family);
  font-size: 20px; /* for desktop this variable is not defined */
  font-weight: 500;
  color: var(--heading-color); /*333*/
  padding-bottom: 5px; 
  border-bottom: 4px solid var(--heading-border-color);
}
```

2023-04-27 07:26 UTC, chicharr commented on styles/styles.css
> +  border-bottom: 4px solid #0255A5;
Thanks @vdua I will address your comments in the follow-up ticket for the Hero component