changing the buildBlock funcion of FAQPage to put the right content l…
hlxsites/realmadrid pull request #83
Opened 2023-05-19 14:23 UTC by kacemait

Showing the fragment in the right language.

Fix #[63](https://github.com/hlxsites/realmadrid/issues/63)

Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/de/vip-zone/faqs
- After: https://contact-card-language--realmadrid--hlxsites.hlx.page/de/vip-zone/faqs

2023-05-22 12:13 UTC, chicharr requested changes

2023-05-22 12:13 UTC, chicharr commented on scripts/scripts.js
> +  const fragmentBlock = buildBlock('fragment', [[VIP_AREA_LANGUAGE_HOME_PATH[getLanguage()]+'/fragments/contact-card']]);
extract `VIP_AREA_LANGUAGE_HOME_PATH[getLanguage()]` to a method called `getVIPAreaLangRoot`  that can be exported and used in different blocks.
I'm not sure if the double brackets are needed.
Please fix the lint issues.

2023-05-24 09:35 UTC, kacemait commented on scripts/scripts.js
> +  const fragmentBlock = buildBlock('fragment', [[VIP_AREA_LANGUAGE_HOME_PATH[getLanguage()]+'/fragments/contact-card']]);
Just modified with new method called getVIPAreaLangRoot and that can be exported and used.

2023-05-24 12:59 UTC, chicharr approved these changes

2023-05-24 13:00 UTC, merged